### PR TITLE
Tunisia map

### PR DESCRIPTION
**Pull request by aref-lazrek**

### CODE REVIEW

**Comment by VictorCazanave** [comment]
Thanks @aref-lazrek 😃
If I have time, I will review it this weekend.

Could you remove the modifications of `package-lock.json` and `packages/taiwan/taiwan.svg` please?

**Comment by aref-lazrek** [comment]
@VictorCazanave Thank you
Yes it's done

**Comment by VictorCazanave** [comment]
Thanks for your contribution!

**Comment by VictorCazanave** [comment]
@all-contributors please add @aref-lazrek for code

**Comment by VictorCazanave** [comment]
@all-contributors please add @aref-lazrek for code

**Pull request merged**
