### PR TITLE
Add a US counties map

### PR DESCRIPTION
**Pull request by keatonboyle**
This was useful for a project I'm working on, thought I'd share it. Let me know if there are any tweaks I should make to the formatting.

### CODE REVIEW

**Comment by VictorCazanave** [comment]
Thanks @keatonboyle 😃 
If I have time, I will review it this weekend

**Comment by VictorCazanave** [comment]
That's perfect! Thanks again for your contribution 😃

**Comment by VictorCazanave** [comment]
@all-contributors please add @keatonboyle for data

**Comment by VictorCazanave** [comment]
@all-contributors please add @keatonboyle for code

**Comment by VictorCazanave** [comment]
@all-contributors please add @keatonboyle for code

**Comment by VictorCazanave** [comment]
@all-contributors please add @keatonboyle for code

**Comment by soundaridss** [comment]
Can please help me for usa map counties with state border?

**Pull request merged**
